package protocol

import (
	"encoding/binary"
	"errors"

	"github.com/umbra-messenger/core/internal/crypt"
)

// SessionCookie is the plaintext payload struct that gets AEAD-encrypted by the server
// using the ServerCookieKey. It is embedded as a byte slice inside HandshakeChallenge
// and sent back by the client inside VerificationRequest.
// It does NOT contain a MessageType byte because it is never routed as a standalone network message.
type SessionCookie struct {
	// SessionID is the 16-byte unique identifier for the session.
	SessionID [16]byte
	// SessionMasterKey is the 32-byte master key generated by the server to derive session keys.
	SessionMasterKey [32]byte
	// SessionToken is the 32-byte proof-of-work artifact.
	SessionToken [32]byte
	// ClientExchangePub is the client's ephemeral X25519 public key.
	ClientExchangePub []byte
	// ClientSignPub is the client's ephemeral Ed25519 public key.
	ClientSignPub []byte
}

func (s *SessionCookie) MarshalBinary() ([]byte, error) {
	if s.ClientExchangePub == nil || s.ClientSignPub == nil {
		return nil, errors.New("protocol: SessionCookie contains nil slices")
	}

	exchange_pub_len := uint64(len(s.ClientExchangePub))
	sign_pub_len := uint64(len(s.ClientSignPub))

	// 16 (session_id) + 32 (master_key) + 32 (token) + 8 (len1) + data1 + 8 (len2) + data2 + 16 (checksum)
	total_size := 16 + 32 + 32 + 8 + int(exchange_pub_len) + 8 + int(sign_pub_len) + 16
	buf := make([]byte, total_size)
	offset := 0

	// 1. SessionID (Fixed 16 bytes)
	copy(buf[offset:offset+16], s.SessionID[:])
	offset += 16

	// 2. SessionMasterKey (Fixed 32 bytes)
	copy(buf[offset:offset+32], s.SessionMasterKey[:])
	offset += 32

	// 3. SessionToken (Fixed 32 bytes)
	copy(buf[offset:offset+32], s.SessionToken[:])
	offset += 32

	// 4. ClientExchangePub
	binary.BigEndian.PutUint64(buf[offset:offset+8], exchange_pub_len)
	offset += 8
	copy(buf[offset:offset+int(exchange_pub_len)], s.ClientExchangePub)
	offset += int(exchange_pub_len)

	// 5. ClientSignPub
	binary.BigEndian.PutUint64(buf[offset:offset+8], sign_pub_len)
	offset += 8
	copy(buf[offset:offset+int(sign_pub_len)], s.ClientSignPub)
	offset += int(sign_pub_len)

	// 6. Checksum
	checksum := crypt.Checksum(buf[:offset])
	copy(buf[offset:offset+16], checksum[:])

	return buf, nil
}

func (s *SessionCookie) UnmarshalBinary(data []byte) error {
	// Min size: 16 + 32 + 32 + 8*2 (lengths) + 16 (checksum) = 112 bytes
	const min_size = 16 + 32 + 32 + 16 + 16
	if len(data) < min_size {
		return errors.New("protocol: data too short for SessionCookie")
	}

	payload_length := len(data) - 16
	var received_checksum [16]byte
	copy(received_checksum[:], data[payload_length:])

	expected_checksum := crypt.Checksum(data[:payload_length])
	if received_checksum != expected_checksum {
		return errors.New("protocol: checksum mismatch in SessionCookie")
	}

	offset := 0

	// 1. SessionID (Fixed 16 bytes)
	if offset+16 > payload_length {
		return errors.New("protocol: underflow reading SessionID")
	}
	copy(s.SessionID[:], data[offset:offset+16])
	offset += 16

	// 2. SessionMasterKey (Fixed 32 bytes)
	if offset+32 > payload_length {
		return errors.New("protocol: underflow reading SessionMasterKey")
	}
	copy(s.SessionMasterKey[:], data[offset:offset+32])
	offset += 32

	// 3. SessionToken (Fixed 32 bytes)
	if offset+32 > payload_length {
		return errors.New("protocol: underflow reading SessionToken")
	}
	copy(s.SessionToken[:], data[offset:offset+32])
	offset += 32

	// 4. ClientExchangePub
	if offset+8 > payload_length {
		return errors.New("protocol: underflow reading ClientExchangePub length")
	}
	exchange_pub_len := binary.BigEndian.Uint64(data[offset : offset+8])
	offset += 8
	if offset+int(exchange_pub_len) > payload_length {
		return errors.New("protocol: underflow reading ClientExchangePub data")
	}
	s.ClientExchangePub = make([]byte, exchange_pub_len)
	copy(s.ClientExchangePub, data[offset:offset+int(exchange_pub_len)])
	offset += int(exchange_pub_len)

	// 5. ClientSignPub
	if offset+8 > payload_length {
		return errors.New("protocol: underflow reading ClientSignPub length")
	}
	sign_pub_len := binary.BigEndian.Uint64(data[offset : offset+8])
	offset += 8
	if offset+int(sign_pub_len) > payload_length {
		return errors.New("protocol: underflow reading ClientSignPub data")
	}
	s.ClientSignPub = make([]byte, sign_pub_len)
	copy(s.ClientSignPub, data[offset:offset+int(sign_pub_len)])
	offset += int(sign_pub_len)

	if offset != payload_length {
		return errors.New("protocol: unexpected trailing data in SessionCookie")
	}

	return nil
}
